"""
@file: gemini_api.py
@author: Jambaldorj Munkhsoyol

This module provides a function to interact with Gemini API to generate
a user-friendly summary of raw weather data. It retrieves the API key from
environment variables, initializes the Gemini client, and defines a function
to generate the summary based on the provided weather data.
"""

import os
from google import genai

MODEL_NAME = "gemini-2.5-flash-lite"

"""
Retrieves the Gemini API key from environment variables.
@return: The Gemini API key as a string.
@raises RuntimeError: If the GEMINI_API_KEY environment variable is not set."""
def _get_api_key():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set")
    return api_key

CLIENT = genai.Client(api_key=_get_api_key())

"""
Generates a user-friendly summary of raw weather data using Gemini API.
@param weather_data: A dictionary containing current weather and forecast data.
@return: A string summary generated by Gemini API.
"""
def get_gemini_response(weather_data):
    prompt = f"""
    Raw weather data is provided below:
    {weather_data}
    Using it, write a short, user-friendly summary of it.
    """

    return CLIENT.models.generate_content(
        model=MODEL_NAME,
        contents=prompt
    ).text